name: Terraform Plan

on:
  push:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 65961c6d-de88-44d4-9864-1fef1d5cc522
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: 3c286043-98c2-4679-aa9a-de40490ad27a
      ARM_TENANT_ID: a88ae17f-e646-4b80-a909-25db6b749d30

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Log In To Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan
